spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost:49154}/${DB_NAME:online_shop_db}
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:masterpass}
    jpa:
        hibernate:
            ddl-auto: none
