spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:postgres_db:5432}/${DB_NAME:online_shop_db}
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka/}
