spring:
    datasource:
        url: jdbc:postgresql://postgres-db:5432/online_shop_db
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://discovery-service:8761/eureka/
